include:
  - project: 'nstart/pipeline-library'
    file: '/.django-ci.yml'

variables:
  SONAR_PROJECT_KEY: "tsoud-geoservices-geoservice-template"

flake8-lint:
  image: repo.nstart.cloud/dockerhub/python:3.11-slim

sonarqube-scan:
  image: repo.nstart.cloud/dockerhub/sonarsource/sonar-scanner-cli:latest
  stage: sonar
  variables:
    GIT_DEPTH: "0"
  script:
    - sonar-scanner -Dsonar.projectKey="${SONAR_PROJECT_KEY}" -Dsonar.host.url="${SONAR_HOST_URL}" -Dsonar.token="${SONAR_TOKEN}" -Dsonar.sources="."
  allow_failure: true
